---

- name: Create User
  gather_facts: false
  hosts: dev
  become: true
  tasks:

    - name: Create a folder named after the user in /tmp
      file:
          path: "/tmp/{{user_name}}"
          state: directory
          mode: '0755'

    - name: Create a file with a template
      template:
        src: "motd.j2"
        dest: /etc/motd

    - name: Ensure group "nginx" exists
      ansible.builtin.group:
        name: nginx
        state: present

    - name: Create a user
      user:
        name: "{{user_name}}"
        groups: "nginx"
        append: true # Do not remove existing groups.
